//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KollageBurst_WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KollageBurst_WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutButtonText {
            get {
                return ResourceManager.GetString("AppBarAboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string AppBarOpenButtonText {
            get {
                return ResourceManager.GetString("AppBarOpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSaveButtonText {
            get {
                return ResourceManager.GetString("AppBarSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingsButtonText {
            get {
                return ResourceManager.GetString("AppBarSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share....
        /// </summary>
        public static string AppBarShareButtonText {
            get {
                return ResourceManager.GetString("AppBarShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KollageBurst.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horizontal resolution: .
        /// </summary>
        public static string HorizontalResolutionText {
            get {
                return ResourceManager.GetString("HorizontalResolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo saved!.
        /// </summary>
        public static string PhotoSavedConfirmationText {
            get {
                return ResourceManager.GetString("PhotoSavedConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing photo....
        /// </summary>
        public static string ProcessingPhotoText {
            get {
                return ResourceManager.GetString("ProcessingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving photo....
        /// </summary>
        public static string SavingPhotoText {
            get {
                return ResourceManager.GetString("SavingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitleText {
            get {
                return ResourceManager.GetString("SettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use original image.
        /// </summary>
        public static string UseOriginalText {
            get {
                return ResourceManager.GetString("UseOriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical resolution: .
        /// </summary>
        public static string VerticalResolutionText {
            get {
                return ResourceManager.GetString("VerticalResolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please choose photo first..
        /// </summary>
        public static string WarningPickPhotoText {
            get {
                return ResourceManager.GetString("WarningPickPhotoText", resourceCulture);
            }
        }
    }
}
